name: Deploy Prod S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: npm i

      - name: 빌드하기
        run: npm run build

      - name: AWS 인증 절차
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: S3 기존 파일들 전체 삭제
        run: aws s3 rm --recursive s3://prod-ozflow

      - name: S3 에 dist 파일 업로드
        run: aws s3 cp ./dist s3://prod-ozflow/ --recursive

      - name: 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id E3GGGHI2BMDQW0 --paths "/*"
